<?php
if(Session::get('autenticado'))
{
    ?>
    <div class="header navbar navbar-inverse ">
        <!-- BEGIN TOP NAVIGATION BAR -->
        <div class="navbar-inner">

            <div class="header-seperation" >
                <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
                    <li class="dropdown">
                        <a id="main-menu-toggle" href="#main-menu">
                            <div class="iconset top-menu-toggle-white">
                                <i class="fa fa-bars"></i>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- BEGIN LOGO-->
                <a href="/"><img src="/public/assets/images/logo_e.png" class="img-responsive  text-center" alt=""  data-src="/public/assets/images/logo_e.png"/></a>
                <!-- END LOGO-->

            </div>
            <!-- END RESPONSIVE MENU TOGGLER -->
            
            <div class="header-quick-nav" >
                <!-- BEGIN TOP NAVIGATION MENU -->
                <div class="pull-left">
                    <ul class="nav quick-section">
                        <li class="quicklinks"> <a href="#" class="" id="layout-condensed-toggle" >
                                <div class="iconset top-menu-toggle-dark"></div>
                            </a> </li>
                    </ul>

                    <!--<ul class="nav quick-section">
                        <li class="quicklinks"> <a href="#" class="" >
                                <div class="iconset top-reload"></div>
                            </a> </li>
                        <li class="quicklinks"> <span class="h-seperate"></span></li>
                        <li class="quicklinks"> <a href="#" class="" >
                                <div class="iconset top-tiles"></div>
                            </a> </li>
                        <li class="m-r-10 input-prepend inside search-form no-boarder"> <span class="add-on"> <span class="iconset top-search"></span></span>
                            <input name="" type="text"  class="no-boarder " placeholder="Search Dashboard" style="width:250px;">
                        </li>
                    </ul>-->
                </div>
                
                <!-- END TOP NAVIGATION MENU -->

                <!-- BEGIN CHAT TOGGLER -->
                <div class="pull-right">
                    <div class="chat-toggler">

                        
                        <a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom"  data-content='' data-toggle="dropdown" data-original-title="Notifications">
                            <div class="user-details">
                                <div class="username"> <span class="badge badge-important" id="notifications_number" data-value="0">0</span> <?php echo $_SESSION['first_name']; ?> <span class="bold"> <?php echo $_SESSION['last_name'];?></span></div>
                            </div>
                            <div class="iconset top-down-arrow"></div>

                        </a>
                        <div id="notification-list" style="display:none" >
                            <div style="width:300px" >
                                <div class="notification-messages info">

                                </div>
                            </div>
                        </div>

                    </div>
                    <ul class="nav quick-section ">
                        <li class="quicklinks"> 
                            <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
                                <i class="fa fa-user"></i>
                                <div class="iconset top-chat-dark "></div>
                            </a>
                            <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
                                <!--<li><a href="user-profile.html"> My Account</a> </li>
                                <li><a href="calender.html">My Calendar</a> </li>
                                <li><a href="email.html"> My Inbox&nbsp;&nbsp;<span class="badge badge-important animated bounceIn">2</span></a> </li>
                                <li class="divider"></li>-->
                                <li><a href="/logout"><i class="fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
                            </ul>
                        </li>
                        
                       <li class="quicklinks"> <span class="h-seperate"></span></li>

                    </ul>
                </div>
                <!-- END CHAT TOGGLER -->
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END TOP NAVIGATION BAR -->
    </div>

    
    <!-- END HEADER -->
    <?php
}

?>

    <?php
    if(Session::get('autenticado'))
    {
        ?>
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar" id="main-menu">
            <!-- BEGIN MINI-PROFILE -->
            <div class="page-sidebar-wrapper scrollbar-dynamic" id="main-menu-wrapper">

                <!-- BEGIN SIDEBAR MENU -->
                <ul>
                <?php
                switch($_SESSION['user_type']) {
                    case 'enterprise':
                        include_once('menu/menu-enterprise.php');
                        break;
                    case 'administrator':
                        include_once('menu/menu-admin.php');
                        break;
                    case 'verifier':
                        include_once('menu/menu-verifier.php');
                        break;
                    case 'traveler':
                        include_once('menu/menu-traveler.php');
                        break;
                    case 'content':
                        include_once('menu/menu-content.php');
                        break;
                    default:
                        include_once('menu/menu-user.php');
                        break;
                }
                ?>
                </ul>

                
                <div class="clearfix"></div>
                <!-- END SIDEBAR MENU -->
            </div>
        </div>

        <!-- END SIDEBAR -->
        <?php
    }

    ?>

    